<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Lab02_QuanLyMang</RootNamespace>
    <AssemblyName>Lab02_QuanLyMang</AssemblyName>
  </PropertyGroup>

</Project>
