<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lab01_ThongTinCaNhan</RootNamespace>
    <AssemblyName>Lab01_ThongTinCaNhan</AssemblyName>
  </PropertyGroup>

</Project>
